### ISSUE TITLE
Evidence for claim

### ISSUE THREAD

**Issue by jd1378** [sarfraznawaz2005/laravel-sse#2]
Hi
Thanks for creating this package
Please don't take me wrong by the following and I'm not trying to be mean,
but do you actually have evidence on that websockets being better than SSE in consuming server resources ?
in the readme you have said: 

> Server Sent Events technology consumes server resources so use it sparingly or **better** use Web Sockets **instead**.

Please clarify if I got it wrong
because my findings are the exact opposite of this

**Comment by sarfraznawaz2005** [comment]
https://stackoverflow.com/questions/5195452/websockets-vs-server-sent-events-eventsource

**Comment by jd1378** [comment]
well I had read that as well,
first of all it depends on the use case
and then your answer still does not answer my question
if the main disadvantage of SSE is connection limit, then maybe also take a look at this:
https://www.smashingmagazine.com/2018/02/sse-websockets-data-flow-http2/

**Comment by sarfraznawaz2005** [comment]
This package is not about benchmarking or comparisions. The package offers SSE and assumes user of this package knows when to use sse vs sockets. So yes you should be able to decide.

**Comment by jd1378** [comment]
True, but then those who are just starting may find your word misleading about one being better than the other
And I appreciate your good intention of giving a heads up about the resource consumption of SSE
but don't take it personal overall ;)

**Comment by sarfraznawaz2005** [comment]
I understand, In fact I should delete the note, up to user to decide, thanks
