### ISSUE TITLE
How to apply middleware to the exposed sse route?

### ISSUE THREAD

**Issue by ZRktty** [sarfraznawaz2005/laravel-sse#7]
I'm using a standalone frontend app in which I want to subscribe for the SSE events but the initialization of the EventSourse('SSE_PUBLIC_ROUTE') fails because of CORS.  

Currently, the route added by the package in `vendor/sarfraznawaz2005/laravel-sse/src/Http/routes.php`
does not seems to be extensible with middleware.

Is there a way to apply middleware to it?

I tried overriding the route defined in the package in the `routes.php` with the following:

```php
Route::group(
    [
    'namespace' => 'Sarfraznawaz2005\SSE\Http\Controllers',
    'prefix' => 'sse',
    'middleware' => ['cors']
    ],
    static function () {
        Route::get('stream', 'SSEController@stream');
    }
);
```

**Comment by sarfraznawaz2005** [comment]
It is not supported but since I am busy, a PR is welcome. If you want to get an idea of how to allow custom middlwares, you can take a look at source of this package:

https://github.com/sarfraznawaz2005/meter
