### ISSUE TITLE
Multiple events sent in controller but only last arrives in client

### ISSUE THREAD

**Issue by ZRktty** [sarfraznawaz2005/laravel-sse#8]
Hello!

I'm sensing 3 SSE events as  following code shows in my laravel app's  controller:

```php
 public function upload(Request $request) {

        SSEFacade::notify('test a', $type = 'info', $event = 'message');
        SSEFacade::notify('test b ', $type = 'info', $event = 'message');
        SSEFacade::notify('test c', $type = 'info', $event = 'message');

        return response()->json([
                'msg' => 'hello',
            ], 200);
        
```     
Then I send a request on the controller function only the last event arrives with the message 'test c'.

Expecting that all three events should arrive.

**Comment by sarfraznawaz2005** [comment]
You should send an array instead of individual events. And then you might need to modify front end code a bit to account for that. See "Customizing SSE Events" section for more details.
